name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set variables
      run: |
        echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv sync

    - name: Build the prod site
      run: |
        pipenv run invoke publish

    # - name: Deploy to GitHub Pages
    #   uses: JamesIves/github-pages-deploy-action@master
    #   if: success()
    #   env:
    #     ACCESS_TOKEN: ${{ secrets.GH_PAT }}
    #     BASE_BRANCH: master
    #     BRANCH: gh-pages
    #     FOLDER: output